[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"
  targetPort = 8080
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
