create table teachers (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null unique,
  date_of_birth date not null
);
