create type attendance_status as enum ('present', 'absent', 'late');

create table attendance (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students (id) on delete cascade,
  class_id bigint not null references classes (id) on delete cascade,
  date date not null,
  status attendance_status not null,
  remarks text,
  unique (student_id, class_id, date)
);
